"""Build-time replacement methods for the existing Qt window (not imported at runtime)."""
def init_ui(self):
    self.setObjectName('perceptionRoot')
    self.setFont(QFont('Noto Sans CJK SC', 11))
    self.setStyleSheet(LIGHT_STYLE)
    self._camera_received = 0.0
    self._rtk_connected = False
    root = QVBoxLayout(self)
    root.setContentsMargins(24, 20, 24, 20)
    root.setSpacing(16)

    header = QHBoxLayout()
    header.setSpacing(16)
    mark = QLabel('RK')
    mark.setFixedSize(52, 52)
    mark.setAlignment(Qt.AlignCenter)
    mark.setStyleSheet('background:#DFF2F0;color:#087F83;border-radius:12px;font-size:22px;font-weight:700;')
    header.addWidget(mark)
    titles = QVBoxLayout()
    titles.setSpacing(3)
    title = QLabel('环境感知')
    title.setStyleSheet('font-size:27px;font-weight:700;color:#193044;')
    subtitle = QLabel('RK3588  /  实时监测')
    subtitle.setStyleSheet('font-size:14px;color:#66788A;')
    titles.addWidget(title)
    titles.addWidget(subtitle)
    header.addLayout(titles)
    header.addStretch()
    self.lidar_badge = QLabel('雷达 · 等待数据')
    self.camera_badge = QLabel('相机 · 等待数据')
    self.dev_badge = QLabel('定位 · 未连接')
    for badge in (self.lidar_badge, self.camera_badge, self.dev_badge):
        badge.setStyleSheet(chip_style('muted'))
        header.addWidget(badge)
    self.rtk_details_btn = QPushButton('定位详情')
    self.rtk_details_btn.clicked.connect(self.open_rtk_details)
    header.addWidget(self.rtk_details_btn)
    self.btn_fs = QPushButton('窗口模式')
    self.btn_fs.clicked.connect(self.toggle_fullscreen)
    header.addWidget(self.btn_fs)
    self.btn_close = QPushButton('×')
    self.btn_close.setFixedSize(44, 44)
    self.btn_close.setAccessibleName('关闭界面')
    self.btn_close.setToolTip('关闭界面')
    self.btn_close.setStyleSheet('font-size:23px;padding:0;color:#607488;')
    self.btn_close.clicked.connect(self.close)
    header.addWidget(self.btn_close)
    root.addLayout(header)

    body = QHBoxLayout()
    body.setSpacing(18)
    camera = QFrame()
    camera.setObjectName('panel')
    cam = QVBoxLayout(camera)
    cam.setContentsMargins(20, 18, 20, 18)
    cam.setSpacing(12)
    top = QHBoxLayout()
    caption = QVBoxLayout()
    caption.setSpacing(3)
    title = QLabel('实时画面')
    title.setStyleSheet('font-size:22px;font-weight:700;')
    subtitle = QLabel('Astra S · 3D 深度相机')
    subtitle.setStyleSheet('font-size:14px;color:#66788A;')
    caption.addWidget(title)
    caption.addWidget(subtitle)
    top.addLayout(caption)
    top.addStretch()
    self.cam_fps_badge = QLabel('-- FPS')
    self.cam_fps_badge.setStyleSheet(chip_style('muted'))
    top.addWidget(self.cam_fps_badge)
    cam.addLayout(top)

    modes = QHBoxLayout()
    modes.setSpacing(8)
    self.btn_ai = QPushButton('AI 目标测距')
    self.btn_rgb = QPushButton('彩色画面')
    self.btn_depth = QPushButton('深度距离图')
    for mode, button in [('ai', self.btn_ai), ('rgb', self.btn_rgb), ('depth', self.btn_depth)]:
        button.setCheckable(True)
        button.setMinimumHeight(44)
        button.clicked.connect(lambda _, m=mode: self.switch_cam_mode(m))
        modes.addWidget(button)
    cam.addLayout(modes)
    self.video_box = QLabel('等待相机画面')
    self.video_box.setAlignment(Qt.AlignCenter)
    self.video_box.setMinimumSize(1, 280)
    self.video_box.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Expanding)
    self.video_box.setStyleSheet('background:#EDF2F5;color:#677A8C;border:1px solid #E2E9EF;border-radius:10px;font-size:17px;')
    cam.addWidget(self.video_box, 1)
    self.cam_dist_badge = QLabel('等待目标信息')
    self.cam_dist_badge.setStyleSheet('color:#344E63;font-size:16px;padding:4px 0;')
    self.cam_dist_badge.setWordWrap(True)
    cam.addWidget(self.cam_dist_badge)

    self.depth_controls = QWidget()
    controls = QVBoxLayout(self.depth_controls)
    controls.setContentsMargins(0, 0, 0, 0)
    controls.setSpacing(8)
    options = QHBoxLayout()
    self.depth_range = QComboBox()
    for label, value in [('近景 0.2–2.0 m', 2000), ('室内 0.2–4.5 m', 4500), ('全程 0.2–5.5 m', 5500)]:
        self.depth_range.addItem(label, value)
    self.depth_range.currentIndexChanged.connect(self.change_depth_range)
    self.depth_style = QComboBox()
    self.depth_style.addItem('平滑展示（非测量）', 'smooth')
    self.depth_style.addItem('原始测量图', 'raw')
    self.depth_style.currentIndexChanged.connect(self.change_depth_range)
    options.addWidget(self.depth_range)
    options.addWidget(self.depth_style)
    controls.addLayout(options)
    self.depth_hint = QLabel('光轴深度 Z / m · 暗灰表示无效或超范围')
    self.depth_hint.setStyleSheet('font-size:13px;color:#64788A;')
    self.depth_hint.setWordWrap(True)
    controls.addWidget(self.depth_hint)
    cam.addWidget(self.depth_controls)
    body.addWidget(camera, 60)

    radar = QFrame()
    radar.setObjectName('panel')
    lidar = QVBoxLayout(radar)
    lidar.setContentsMargins(20, 18, 20, 18)
    lidar.setSpacing(10)
    radar_top = QHBoxLayout()
    title = QLabel('周围环境')
    title.setStyleSheet('font-size:22px;font-weight:700;')
    radar_top.addWidget(title)
    radar_top.addStretch()
    self.pause_lidar = QPushButton('暂停点云')
    self.pause_lidar.setCheckable(True)
    self.pause_lidar.clicked.connect(self.toggle_lidar_pause)
    radar_top.addWidget(self.pause_lidar)
    lidar.addLayout(radar_top)
    subtitle = QLabel('N10P · 360° 激光扫描')
    subtitle.setStyleSheet('font-size:14px;color:#66788A;')
    lidar.addWidget(subtitle)
    self.canvas = RadarCanvas(self)
    lidar.addWidget(self.canvas, 1)
    self.lidar_status = QLabel('等待 N10P 扫描数据')
    self.lidar_status.setStyleSheet('font-size:13px;color:#607488;')
    lidar.addWidget(self.lidar_status)
    legend = QLabel('<span style="color:#CA4653">●</span> &lt; 0.6 m　 <span style="color:#A16B12">●</span> &lt; 1.2 m　 <span style="color:#087F83">●</span> 正常回波')
    legend.setStyleSheet('color:#607488;font-size:13px;padding:4px 0;')
    lidar.addWidget(legend)
    ranges = QHBoxLayout()
    label = QLabel('显示范围')
    label.setStyleSheet('font-size:14px;color:#607488;')
    ranges.addWidget(label)
    self.range_buttons = {}
    for radius in (3, 5, 8, 12):
        button = QPushButton(f'{radius} m')
        button.setCheckable(True)
        button.setChecked(radius == 5)
        button.clicked.connect(lambda _, r=radius: self.set_lidar_range(r))
        self.range_buttons[radius] = button
        ranges.addWidget(button)
    lidar.addLayout(ranges)
    body.addWidget(radar, 40)
    root.addLayout(body, 1)

    metrics = QHBoxLayout()
    metrics.setSpacing(14)
    self.front_lbl = self._create_card('前方 · 0°', '--')
    self.left_lbl = self._create_card('左侧 · 90°', '--')
    self.right_lbl = self._create_card('右侧 · 270°', '--')
    self.back_lbl = self._create_card('后方 · 180°', '--')
    for card in (self.front_lbl, self.left_lbl, self.right_lbl, self.back_lbl):
        metrics.addWidget(card)
    root.addLayout(metrics)
    self.alarm_box = QLabel('雷达等待数据 · 环境状态未知')
    self.alarm_box.setMinimumHeight(48)
    self.alarm_box.setAlignment(Qt.AlignVCenter | Qt.AlignLeft)
    self.alarm_box.setStyleSheet('background:#FFF6E5;color:#8B5D16;border-radius:10px;padding:8px 18px;font-size:16px;')
    root.addWidget(self.alarm_box)

    self.rtk_dialog = QDialog(self)
    self.rtk_dialog.setWindowTitle('定位与设备详情')
    self.rtk_dialog.resize(850, 570)
    self.rtk_dialog.setStyleSheet(LIGHT_STYLE)
    layout = QVBoxLayout(self.rtk_dialog)
    layout.setContentsMargins(24, 24, 24, 24)
    self.rtk_card = self.create_rtk_card()
    layout.addWidget(self.rtk_card, 1)
    close = QPushButton('完成')
    close.clicked.connect(self.rtk_dialog.close)
    layout.addWidget(close, 0, Qt.AlignRight)
    self.update_mode_buttons()
    self.depth_range.setEnabled(False)
    self.depth_style.setEnabled(False)
    self._status_timer = QTimer(self)
    self._status_timer.timeout.connect(self.refresh_connection_badges)
    self._status_timer.start(300)

def _create_card(self, title, val):
    frame = QFrame()
    frame.setObjectName('panel')
    layout = QHBoxLayout(frame)
    layout.setContentsMargins(22, 16, 22, 16)
    text = QLabel(title)
    text.setStyleSheet('font-size:16px;color:#64788A;')
    value = QLabel(val)
    value.setStyleSheet('font-size:30px;font-weight:700;color:#213D51;')
    value.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
    layout.addWidget(text)
    layout.addStretch()
    layout.addWidget(value)
    frame.val_label = value
    frame.setMinimumHeight(90)
    return frame

def create_rtk_card(self):
    card = QFrame()
    layout = QVBoxLayout(card)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(16)
    title = QLabel('卫星定位')
    title.setStyleSheet('font-size:24px;font-weight:700;')
    layout.addWidget(title)
    subtitle = QLabel('C-RTK 2HP · 双天线定位与航向')
    subtitle.setStyleSheet('font-size:15px;color:#64788A;')
    layout.addWidget(subtitle)
    statuses = QHBoxLayout()
    self.rtk_ant1_badge = QLabel('左天线 · 等待数据')
    self.rtk_ant2_badge = QLabel('右天线 · 等待数据')
    for badge in (self.rtk_ant1_badge, self.rtk_ant2_badge):
        badge.setStyleSheet(chip_style('muted'))
        statuses.addWidget(badge)
    statuses.addStretch()
    self.rtk_cors_btn = QPushButton('差分连接设置')
    self.rtk_cors_btn.clicked.connect(self.open_cors_dialog)
    statuses.addWidget(self.rtk_cors_btn)
    layout.addLayout(statuses)
    grid = QGridLayout()
    grid.setSpacing(12)
    specs = [('rtk_sats_ant1_box', '左天线 · 主 ANT1'), ('rtk_sats_ant2_box', '右天线 · 辅 ANT2'),
             ('rtk_sats_sky_box', '天空卫星分布'), ('rtk_heading_box', '航向 / 共视卫星'),
             ('rtk_coord_box', '经纬度'), ('rtk_alt_box', '海拔 / 精度')]
    for i, (name, title) in enumerate(specs):
        metric = self._create_sub_metric(title, '--')
        setattr(self, name, metric)
        grid.addWidget(metric, i // 2, i % 2)
    layout.addLayout(grid, 1)
    return card

def _create_sub_metric(self, title, val):
    frame = QFrame()
    frame.setObjectName('panel')
    layout = QVBoxLayout(frame)
    layout.setContentsMargins(16, 14, 16, 14)
    layout.setSpacing(8)
    text = QLabel(title)
    text.setStyleSheet('font-size:14px;color:#64788A;')
    value = QLabel(val)
    value.setWordWrap(True)
    value.setStyleSheet('font-size:16px;font-weight:600;color:#213D51;')
    layout.addWidget(text)
    layout.addWidget(value)
    frame.val_lbl = value
    return frame

def update_mode_buttons(self):
    for mode, button in [('ai', self.btn_ai), ('rgb', self.btn_rgb), ('depth', self.btn_depth)]:
        button.setChecked(self.cam_mode == mode)
    self.depth_controls.setVisible(self.cam_mode == 'depth')

def open_rtk_details(self):
    self.rtk_dialog.exec_()

def refresh_connection_badges(self):
    now = time.monotonic()
    scan = self.ros_thread.latest_scan
    live = scan is not None and now - scan['received'] + scan.get('source_age', 0) < 0.65
    self.lidar_badge.setText('雷达 · 在线' if live else '雷达 · 等待数据')
    self.lidar_badge.setStyleSheet(chip_style('good' if live else 'muted'))
    if self.cam_mode == 'depth':
        record = self.ros_thread.latest_depth
        live_cam = record is not None and now - record['received'] + record['age'] < 0.6
    else:
        live_cam = self._camera_received > 0 and now - self._camera_received < 1.0
    self.camera_badge.setText('相机 · 在线' if live_cam else '相机 · 等待数据')
    self.camera_badge.setStyleSheet(chip_style('good' if live_cam else 'muted'))
    self.cam_fps_badge.setStyleSheet(chip_style('good' if live_cam else 'muted'))
    if not live_cam:
        self.cam_fps_badge.setText('-- FPS')

def on_rtk_data(self, data):
    self.canvas.set_rtk(data)
    connected = bool(data.get('connected', False))
    fix_q = data.get('fix_quality', 0)
    ant1_used = data.get('ant1_used', data.get('sats_used', 0))
    ant2_used = data.get('ant2_used', 0)
    ant1_fix = data.get('ant1_fix') or ('固定' if fix_q == 4 else '浮点' if fix_q == 5 else '单点' if fix_q > 0 else '搜星中')
    ant2_fix = data.get('ant2_fix') or '搜星中'
    for side, badge, fix in [('左天线', self.rtk_ant1_badge, ant1_fix), ('右天线', self.rtk_ant2_badge, ant2_fix)]:
        badge.setText(f'{side} · {fix}' if connected else f'{side} · 未连接')
        badge.setStyleSheet(chip_style('good' if connected and fix == '固定' else 'warn' if connected else 'muted'))
    self.rtk_sats_ant1_box.val_lbl.setText(f'{ant1_fix}  ·  解算 {ant1_used} / 跟踪 {data.get("ant1_tracked", 0)}')
    self.rtk_sats_ant2_box.val_lbl.setText(f'{ant2_fix}  ·  解算 {ant2_used} / 跟踪 {data.get("ant2_tracked", 0)}')
    self.rtk_sats_sky_box.val_lbl.setText(f'左侧 {data.get("sats_left", 0)} 颗  /  右侧 {data.get("sats_right", 0)} 颗')
    self.rtk_heading_box.val_lbl.setText(f'{data.get("heading", 0):.1f}°  ·  共视 {data.get("heading_sats_common", 0)} 颗' if data.get('has_heading') else '等待航向解算')
    lat, lon = data.get('lat', 0), data.get('lon', 0)
    self.rtk_coord_box.val_lbl.setText(f'{lat:.6f}, {lon:.6f}' if connected and fix_q > 0 else '等待定位解算')
    self.rtk_alt_box.val_lbl.setText(f'{data.get("alt", 0):.1f} m  ·  HDOP {data.get("hdop", 99):.1f}' if connected and fix_q > 0 else '--')
    cors = data.get('cors', {})
    self.cors_dialog.update_cors_status(cors)
    self.dev_badge.setText(f'定位 · {ant1_fix}' if connected else '定位 · 未连接')
    self.dev_badge.setStyleSheet(chip_style('good' if connected and fix_q == 4 else 'warn' if connected else 'muted'))
